--계정생성에 사용했던 스크립트 (system 계정으로 접속해서 실행함)
/*
CREATE USER SEMI IDENTIFIED BY 1234;
GRANT RESOURCE , CONNECT TO SEMI;
ALTER USER SEMI DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
*/


Filter changed files
 42  
sqlRepo/SEMI.sql
Comment on this file
@@ -0,0 +1,42 @@
-- 계정 생성에 사용했던 스크립트 (SYSTEM 계정으로 접속해서 실행함)
/*
CREATE USER SEMI IDENTIFIED BY 1234;
GRANT RESOURCE , CONNECT TO SEMI;
ALTER USER SEMI DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
*/



-- MEMBER
DROP TABLE MEMBER CASCADE CONSTRAINTS;
CREATE TABLE MEMBER(
    NO              NUMBER          PRIMARY KEY 
    , ID            VARCHAR2(100)   NOT NULL UNIQUE
    , PWD           VARCHAR2(100)   NOT NULL
    , NICK          VARCHAR2(100)   NOT NULL
    , HOBBY         VARCHAR2(100)   
    , ENROLL_DATE   TIMESTAMP       DEFAULT SYSDATE
    , QUIT_YN       CHAR(1)         DEFAULT 'N' CHECK( QUIT_YN IN('Y','N') )
);

DROP SEQUENCE SEQ_MEMBER_NO;
CREATE SEQUENCE SEQ_MEMBER_NO NOCACHE;

-- BOARD
DROP TABLE BOARD CASCADE CONSTRAINTS;
CREATE TABLE BOARD(
    NO              NUMBER          PRIMARY KEY
    , TITLE         VARCHAR2(100)   NOT NULL
    , CONTENT       VARCHAR2(400)   NOT NULL
    , WRITER        NUMBER          NOT NULL
    , ENROLL_DATE   TIMESTAMP       DEFAULT SYSDATE
    , DELETE_YN     CHAR(1)         DEFAULT 'N' CHECK( DELETE_YN IN('Y','N') )
    , HIT           NUMBER          DEFAULT 0
    , CONSTRAINT FK_BOARD_MEMBER FOREIGN KEY(WRITER) REFERENCES MEMBER(NO)
);


DROP SEQUENCE SEQ_BOARD_NO;
CREATE SEQUENCE SEQ_BOARD_NO NOCACHE NOCYCLE;

--조회수 증가
--UPDATE BOARD SET HIT = HIT+1 WHERE NO = ?
SELECT * FROM BOARD;

-- ATTACHMENT
DROP TABLE ATTACHMENT CASCADE CONSTRAINTS;
CREATE TABLE ATTACHMENT(
    NO              NUMBER          PRIMARY KEY
    , ORIGIN_NAME   VARCHAR2(100)   
    , CHANGE_NAME   VARCHAR2(100)   NOT NULL
    , REF_BOARD_NO  NUMBER          
    , CONSTRAINT FK_ATTACHMENT_BOARD FOREIGN KEY(REF_BOARD_NO) REFERENCES BOARD(NO)
);

DROP SEQUENCE SEQ_ATTACHMENT_NO;
CREATE SEQUENCE SEQ_ATTACHMENT_NO NOCACHE NOCYCLE;


-- 테스트

SELECT * FROM MEMBER;

SELECT * FROM BOARD WHERE DELETE_YN = 'N';

INSERT INTO BOARD(NO,TITLE,CONTENT,WRITER) VALUES (SEQ_BOARD_NO.NEXTVAL, '제목01', '내용01', 1);
INSERT INTO BOARD(NO,TITLE,CONTENT,WRITER) VALUES (SEQ_BOARD_NO.NEXTVAL, '제목02', '내용02', 2);
INSERT INTO BOARD(NO,TITLE,CONTENT,WRITER) VALUES (SEQ_BOARD_NO.NEXTVAL, '제목03', '내용03', 1);
INSERT INTO BOARD(NO,TITLE,CONTENT,WRITER) VALUES (SEQ_BOARD_NO.NEXTVAL, '제목04', '내용04', 2);
INSERT INTO BOARD(NO,TITLE,CONTENT,WRITER) VALUES (SEQ_BOARD_NO.NEXTVAL, '제목05', '내용05', 1);

COMMIT;

SELECT * 
FROM 
(
    SELECT  ROWNUM AS RNUM
    , TEMP.* 
    FROM --(테이블 같은거 == 결과집합 == 셀렉트 쿼리 결과)
    (
        SELECT 
            B.NO 
            , B.TITLE 
            , B.CONTENT 
            , B.WRITER 
            , B.ENROLL_DATE 
            , M.NICK 
        FROM BOARD B 
        JOIN MEMBER M ON B.WRITER = M.NO 
        WHERE B.DELETE_YN = 'N'
        ORDER BY NO DESC
    ) TEMP
)
WHERE RNUM BETWEEN 1 AND 5;


------연습장


--MESSAGE
DROP TABLE MESSAGE;
CREATE TABLE MESSAGE (
    MSG VARCHAR2(100)
);
--SAMPLE
INSERT INTO MEMBER(NO,ID,PWD,NICK)
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'ADMIN', '1234','관리자');
COMMIT;


SELECT * 
FROM BOARD 
WHERE TITLE = ?
AND CONTENT = ?
AND WRITER = ?
;














