    CREATE USER MINI IDENTIFIED BY 1234;
    GRANT CONNECT,RESOURCE TO MINI;
    
    ALTER USER MINI DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
    
CREATE USER SEMIPJ IDENTIFIED BY 1234;
GRANT RESOURCE , CONNECT TO SEMIPJ;
ALTER USER SEMIPJ DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;